src/components/countdownBadge/CountdownBadge.js
minor fix to correct countdown timer at 0 minutes. SHould display ":00" in red now. Fixes #92
=> correct countdown display at 0 minutes

package.json, src/App.js, src/components/graph/Graph.js, src/pages/login/ForgotPassword.js, src/pages/login/ResetPassword.js, src/pages/tools/queryrules/Rules.js, yarn.lock
Not a functional change, just breaks the code out logically into separate bundles to minimize the prod footprint where possible. 
To test:
Run 'yarn install' for the new deps
Run 'yarn build' to generate prod resources
Run 'yarn analyze' to view the source tree and verify the content of the bundles OR view the bundle files at root/build/static/js, 
verify that the js files include bundles with names beginning **admin**, **unauthed**, and **main**. Deps have bundles beginning with a number, the first (shd begin with "4") contains all 3rd party dependencies not explicitly split into another bundle. Bundle "5" should contain the vaquita dep and its peers jquery and some d3 modules. Bundle "6" will have d3-selection.
=> init bundle reorg. Must run yarn install for new deps

src/pages/admin/manageUsers/ManageUsers.scss, src/pages/paxDetail/evenNotesModal/EventNotesModal.js, src/pages/paxDetail/notification/Notification.js, src/pages/paxDetail/notification/Notification.scss
Issue is that the modal wasn't letting you close it by clicking outside it (which is a no-no), and also fixed a minor layout issue where the user list was spilling outside the modal boundary.
=> Notification Users modal - minor layout misc

src/components/graph/Graph.js, src/pages/paxDetail/PaxDetail.js
Link analysis was making background calls on window resize event even when the page was unmounted. Issue was that the vaquita dependency (jquery) had registered a listener for the resize event that was retained in memory, and which keeps the api in memory when not required. If connected to neo4j, it would continue to make calls to update and redraw itself on each resize event, which is problematic.
Fixed it by capturing the event that triggered the fetch and deregistering it. Somebody owes me a cupcake.
=> prevent vaquita dep from updating in background

src/components/main/Main.css, src/pages/admin/Admin.js, src/pages/tools/Tools.js
fixes #230 . Added the default page layout component (Main) with an extra style to exclude the title component when scrolling for pages where the content height is not fixed like it is for grid pages. Fixed both Admin and Tools landing pages. 
Test by resizing the /admin and /tools pages width and height so the cards drop to two or one column and extend beyond the height of the page. Vertical scroller should appear so you can view all tiles plus a margin at the very bottom.
=> fix missing scroller on admin and tools landing pages

src/pages/flightPax/FlightPax.js
fixes #281 Clicking on the text inside the tab header was not causing the data to reload because the xl8 tab was blocking it. Should work anywhere you click in the tab header now.
=> fix tab xl8 text not triggering tab click handler

src/components/header/Header.js, src/components/header/Header.scss
fix #272 .
To test, change the user firstname and lastname to something very short and check that the Change Password and Logout items in the header dropdown are not clipped on the right edge.
=> push header dropdown to the left

src/components/labelledInput/LabelledInput.js, src/pages/admin/codeEditor/creditcardtype/CreditCardTypeModal.js, src/services/serviceWrapper.js
minor - upper case the credit card type codes in Code Editor, and set the maxlength = 2. Also removed the "Restore" option for new codes that can't be restored from the CreditCardTypeRestore table (no originId).
Will do the same for the remaining types under code editor later.
=> uppercase code and set max length = 2

src/components/raqb/constants.js, src/context/data/LookupContext.js, src/pages/tools/queryrules/QRModal.js, src/services/serviceWrapper.js, src/utils/constants.js
Pull credit card type lookup data into context for use in QBRB dropdown containing description and codes for credit card types.
=> convert credit card type to dropdown

src/components/table/Table.js
Would like to eventually mimic sortIcon function behaviour and feed it the column to determine type of icon returned rather than leaving the logic inside the table element itself. But this works for now.
=> Changed groupBy icons to use font awesome

src/pages/paxDetail/PaxDetail.js, src/pages/paxDetail/uploadAttachment/UploadAttachment.js
-button was moved out of control of UploadAttachment.js, call back no longer attached as it was
-callback routed through PaxDetail.js now to update attachmentRefreshKey
=> Fixed attachment tab list not auto-refreshing on uploading an attachment

src/components/header/Header.js
force reset of live edit mode when the user logs out. This is in prep for the logout workaround ticket where we allow admins in live edit mode to "pseudo logout" so they can see and translate pages outside the authed bundle (TBD).
=> force read mode on logout

src/pages/tools/queryrules/Rules.js
Fixes #383 , all rules data was showing when the Rules page first loads on the "My rules" tab.
=> fix initial tab data fetch

src/pages/flights/Flights.js
fixed the replace function to use a regex when constructing the airport filter array.
Accepts space separated and comma separated codes. Test with strings with combinations of separators and airports like:
`LHR,, DOH FRA IAD`
`IAD   DOH   LHR`
`IAD,DOH,LHR`
`,,  IAD,,, DOH    `
etc
fixes #443
=> Flights - fix the airport filter fxn

src/pages/paxDetail/pnr/PNR.js
fix #523 - remove the extra sort function on the flight legs and use the legNumber field in the dataset.
Issue was that the legs were sorted in the reverse order from the latest leg to the earliest.
=> fix PNR Itinerary flight leg order

src/pages/paxDetail/PaxDetail.js
fixes #540 
update the flight leg stepper when reloading the paxDetail with historical data for the same pax.
To test, find a pax with historical hits (preferably several) and verify that the data in the flightbadge (at the top of the sidebar) stays in sync with the airports displayed at the bottom in the flight leg stepper.
=> retrigger stepper fetch on paxid updated

src/components/raqb/constants.js
fixes #560 
fixed flight leg config.
To test, go to the rule builder and build a rule on the Flight Leg entity like:
`Flight Leg > origin = "AAA"` or
`Flight Leg > destination any_in "AAA, BBB"` etc
Save and re-open it and just verify that the values you select are still showing.
=> fix flight legs not displaying field values

src/pages/paxDetail/PaxDetail.js, src/pages/paxDetail/changeHitStatus/ChangeHitStatus.js
#275 - fix `create hit` and `add to watchlist` action buttons showing up for the wrong roles. Previous fixes overlooked this in the original PR. When logged as View Passenger role, the red buttons still show up even though you can't click them.
To test:
- login as a view passenger role and verify that the red `create hit` and `add to watchlist` buttons are not visible.
- login as a manage watchlist role and verify that the red `add to watchlist` button IS visible but not the 'create manual hits'
=> fix action buttons not hiding

src/App.js, src/components/header/Header.js, src/components/seatChart/SeatChart.js, src/components/seatChart/seat/Seat.js, src/components/seatChart/seat/Seat.scss, src/context/roleAuthenticator/RoleAuthenticator.js, src/pages/admin/codeEditor/CodeEditor.js, src/pages/admin/errorLog/ErrorLog.js, src/pages/login/ResetPassword.js, src/pages/login/SignUp.js, src/utils/constants.js
Fixes #563, #561, #211 
- Fixed issue with router paths
- Added role validation on the watchlist page (links were hidden but the page was still accessible)
- Removed erroneous route granting full access to the seats page
- Fixed error and broken css when navving directly to seat-chart without going through paxdetail first
- Fixed broken rerouting in Code Editor that prevented backward navigation with the browser back button.
=> fix routing, wl permissions, reset page

src/pages/admin/loaderStats/LoaderStats.js
fixes #412 
Prevent 0 date timestamps from being converted to 1970 date. Showing "--" instead.
also removed unnecessary form refresh token.
Can only be tested on a fresh install with no rules/hits/messages run.
=> fix null analyzed date

src/App.js, src/components/header/Header.js, src/pages/login/Login.js, src/pages/login/SignUp.js
Fix duplicate redirect/link when logging out which was causing an infinite loop.
Fix blank sign-up page link.
Added redundant logout and exit live edit code handle direct navs to login page
Fixes #597 #592
=> fix duplicate redirect to login

src/components/table/Table.js
-Key value on the row elements for when rows were aggregated wasn't present so it failed to construct both the rows themselves and the expanded sub-rows
-Key value now checks for if "isgroupBy" and assigns the key from that row's groupByVal instead.
=> Updated the key value on the row element

src/pages/vetting/Vetting.js
-Filter form reset button destroys all fields, then uses an init param function to fill if it exists
-vetting filter required more fields than other filters, hence why flight filter does not have problems
-added init params to init param call back to give default search on reset press.
=> Added initial state for vetting filter form

src/services/baseService.js, src/services/serviceWrapper.js
-file uploads needs a special header, trying to assign content-type prevents the webkit form boundary from being used automatically as part of the content-type. The multipart file endpoint requires boundaries to be able to be read successfully. The easiest way to do this is to let the form automatically generate the content-type for this request. I.E. we have a header with no content-type for file uploads.
=> Adds missing header to attachments

src/utils/utils.js
Describe the bug
A clear and concise description of what the bug is.
Watchlist Imports Date Without 0
To Reproduce
Steps to reproduce the behavior:
Import watchlist, review wl_item database, review dob field.
Expected behavior
dob field in watchlist item has preceding 0s where appropriate.
e.g. 1982-02-02 instead of 1982-2-2
Additional context
Ticket for GUI
#654
Companion ticket in GTAS
US-CBP/GTAS#2016
A leading 0 must be applied to dates otherwise the fuzzy matching GTAS
uses has an error parsing dates from watchlist items.
=> Update the way wl dates are parsed to a string.

src/pages/admin/fileDownload/FileDownload.js, src/pages/paxDetail/uploadAttachment/UploadAttachment.js, src/services/genericService.js, src/services/serviceWrapper.js
-window.open is problematic for when we try to pass custom headers due to its locked down nature
-replaced window.open with normal response entity service call
-made download wrapper in order to pass response entity (blob) to, to create the normal download window trigger.
-need to pass filename through service now for things that initiate a 'download'
-Same bug existed on log files, this should be fixed by that.
-generic service modified for given urls to convert response to blob when appropriate
fixes #643
=> Fix for download attachment bug

src/components/seatChart/searchSeat/SearchSeat.js
Fixes #632 Seat search middle name not working
Minor. `areEqual` does a toUpperCase on the input params which fails silently if either is null. Just added the `alt` fxn.
=> null check on search comparison

src/pages/admin/signUpRequests/SignUpRequests.js
fixes #650 - Reset not displaying the correct results
Set the initial form data to select signup requests in the "NEW" status by default.
=> set the initial state for the signup request filterform

src/components/countdownBadge/CountdownBadge.js
fixes #657 - removes the extra space on the CountdownBadge between the "-" sign and the time left.
=> remove extra space after minus sign

src/pages/vetting/Vetting.js
Fixes #652 - Vetting hour range filter not working
So the issue was that the data returned from a search was consistently outside the selected range filters. The end date calculation was treating the terms as a _string concatenation_. So `endDate.getHours() + endRange` // resolved to an equation like 11 + "0" => 110, instead of 11 + 0 = 11, so the end date was off by months.
It worked fine for the startDate since js will coerce both terms to numbers for subtraction, but for addition strings take precedent. Fix was to first convert the range string to number: number + +string => number + number.
=> fix start date bug, fix date calc, fix toggle ref

src/App.scss, src/components/filterForm2/FilterForm.css
fixes #642 - makes the datepicker calendar popups fully visible for all data/views.
popped the calendar popup out of the sidebar, and then had to adjust the parent containers to re-enable the vertical scrollbar for short viewports.
To Test:
1. go to the vetting page
2. select "Show Date Time picker"
3. click on the year, month or day portion of the date to launch the calendar and verify you can view all days in the month
4. click the popup header (month YYYY) and verify you can view all months in the year
5. keep clicking the header and ensure you can view all years or year groups
6. drag the browser edge to make the window shorter vertically so it hides at least the Reset and Search buttons and ensure that the sidebar displays a scrollbar so that all the contents are still accessible
=> reset dp layout, fix background scroll behavior

package-lock.json, package.json, src/components/stepper/Stepper.js
bump bootstrap dep from the rc version. Just click around the app to verify bootstrap-related js and jquery still behave as expected (eg, the navbar dropdowns, popovers, modals, etc)
Fixes #690
=> upgrade react bootstrap to 1.5.0 from rc

src/App.scss, src/components/cardWithTable/CardWithTable.js, src/components/overlay/Overlay.scss, src/components/paxInfo/PaxInfo.js, src/components/stepper/Stepper.js, src/components/tooltipWrapper/TooltipWrapper.js, src/pages/flightPax/FlightPax.js, src/pages/flights/Flights.js
Fixes #678 - This is a very minor fix, but impacts performance. Just added a second test to CardWithTable to display a plain <td> element rather than defaulting to either of the tooltip components.
Also updated the css for both tooltip implementations to use the dark popover style and green link text.
Ran a few dozen tests comparing them, and was able to reduce the the paxdetail page cpu load spike (where the cpu was above 5% on page load) from a range of 8 - 10 seconds down to 4 - 6 seconds. Peak cpu seconds (at 100%) went from 4-5 seconds down to 1-3 seconds (avg about 2.2) over 11 tests. Also ran several lighthouse reports against the two, and while most metrics were more or less a wash, the time to interactive ranged from .8 seconds to 3.3 seconds faster with the latest changes. Lots …
=> CardWithTable - don't return overlays for fields without tooltips

src/components/inputs/label/Label.js, src/components/labelledInput/LabelledInput.css, src/components/labelledInput/LabelledInput.js, src/pages/home/LangModal.js
fixes #696 - Translation modal text running off the edge.
When the **Default Text** was long, it was not wrapping.
1. Turn on translation mode
2. Go to PaxDetail
3. click the "Add to Watchlist" fab button
4. click to edit the text on the Add modal
Looks like this now. Added italics so it stands out a bit more. Not sure how I feel about it.
=> fix translation modal css

src/pages/flightPax/FlightPax.js, src/utils/constants.js, src/utils/utils.js
Fixes #704 - paxdetail DOB filter inaccurate
the DOB column has a hidden sortable date that is used by the table to sort the date strings correctly. Problem is that it included time parts, so for any record the sortable date would be **YYYYMMDD000000**. This ensures the sort works, but breaks the filter because now all records will match when you type in **0**. You also get erroneous results if you type in **80** expecting to match 1980 or age 80 because you will also get records whose sortable date is like YYY**80**MDD, YYYYM**80**D, etc.
* Fixed the sortable function to exclude the timepart zeroes and added an unmapped character to the result string as a delimiter so we don't get matches across different date parts.
* Left padded the DOB months and days
To test
1. go to paxdetail
2. …
=> fix dob filter, left-zero-pad dates

src/pages/flightPax/FlightPax.js
fixes #706 - remove Flight pax Hit Aggregate filter.
The filter is unnecessary and doesn't actually work.
=> remove filter

src/pages/flightPax/FlightPax.js
-fixes group by issue on dev
-Anytime custom cells are used in any tables groupBy fails due to looking for generic values based on the accessors given in it, which when it constructs the new row will not actually be accessible at that level. A custom aggregator must be constructed and passed in order to satisfy its needs. In this case since need no complex aggregation on the field, we simply can leave it empty.
=> fix for groupBy bug on dev

public/index.html
fixes #720 - SharedArrayBuffer
This replaces the global SharedArrayBuffer object with ArrayBuffer. There is no functional change, so just do a smoke test. Click around the pages and make sure there are no surprises.
=> fix references to SharedArrayBuffer

src/pages/vetting/Vetting.js
Fixes #698 - Vetting fetch running 3 times on load
-Was calling on each list of categories being fetched rather than waiting for all data to be fetched, loaded, THEN make a request based on those parameters
-implemented hasData check for the types of categories, if both present THEN make call.
-removed init param request call since this is unnecessary since data is called AFTER init params are set based on table first time load anyway?
-Still extra call based on init param load, but this shaves requests down by 33%, there are solutions for the other. Will discuss before fixig.
=> Fix for multi-request vetting issue

src/components/filterForm2/FilterForm.css
Fixes #763 - Sidebar calendar popovers are hidden.
We are just removing the popovers for now for cleaner sidebar display. Verify that the popover cannot be launched from these pages.
Vetting
poe
audit log
error log
These popovers for these modals should also not display because they were already manually disabled.
watchlist modal
qbrb modal (end date input)
=> hide the datetime picker's calendar popover

src/components/filterForm2/FilterForm.js, src/pages/vetting/Vetting.js, src/utils/utils.js
-Added init table state to table on vetting page
-Added sortBy array values, passing high cat variable name for back end sorting correctly
-datefilter/daterange are bundled as an array of values for props of the filter form
-This caused emergent bug that prevented children from having their datafields properly read when present
-Filterform modified to drill minimally 1 layer deeper seeking children in order to retrieve array for proper field assignment
The table should automatically sort the front-end now based on hit category AND the back end now receives a request with the appropriate sortBy filter.
Secondly, both data range and date picker should now properly make requests with their appropriate date ranges on the vetting page.
this fixes #596 and #760
=> Fixes for hit category default sort and date range values not passed

src/context/data/LookupContext.js, src/pages/tools/queryrules/QRModal.js
fixes #787  - QRModal screen whiteout error
Updated the fetch from Lookup context to prevent filtering by favorites when pulling all data including airports. Other types were not affected because they do not have a favorites column in the IDB table.
=> QBRB - bypass favorites filter for query builder calls

src/pages/vetting/Vetting.css, src/pages/vetting/Vetting.js
Fixes #374 Vetting short text is truncated at the server.
Run with backend branch [fix/vettingHitsResults](https://github.com/US-CBP/GTAS/pull/2055)
This is the final fix to the vetting page column updates. Issue was that the backend was unhelpfully pre-truncating the hits details text in addition to the front-end truncation with tooltip. We now pull the full text from the backend with the title, severity, etc concatenated into one string (which should probably be broken back out into separate fields eventually).
Also dropped all the unnecessary unused fields from the DTO/VOs, services, and model since the footprint of the resultset is already pretty big and we do not currently cache or gzip any of it. 
Hits col now has a fixed width, no-wrap, and can show the full hit title:
=> Vetting - Hits col data truncated

src/components/kanban/Kanban.js
fixes #775 - POE duplicate lane name translations.
When entering translation mode, the POE lane names should no longer be translatable as they are already editable in Admin > Lookout Lanes.
=> remove lane name xl8 tags

src/components/lazyImage/LazyImage.js, src/components/lazyImage/LazyImage.scss
fixes #783 - carrier image not square
Fixes the little icon dimensions (not the popover ones) and the flightbadge carrier icon, which is now 50 x 50.
=> fix icon dimensions

src/components/kanban/Kanban.js
Fixes #814 
Added flight number and flightpax link to POE tile.
Also added tooltip wrapper to flight id to match functionality in rest of site for carrier codes.
This requires a PR on the backend of the same name to be run.
=> Add flightpax link and flight number to POE tile

src/App.scss, src/components/filterForm2/FilterForm.css, src/components/sidenavContainer/SidenavContainer.scss
minor css conflict. One of the default styles to keep the sidebar text visible above the background image was being applied inconsistently because the style was nested under a control where it can't always (but can sometimes?) be accessed outside the component because of a reason.
Moved the css up to app (global) so the style accessible globally.
Below, the text is at least theoretically more readable with the blur.
=> minor - correct missing blur on paxdetail sidebar

src/components/table/Table.js
minor - restores the table filter row on all pages that use it.
fixes #819 - Table filters missing
=> fix missing table filter cols

src/components/countdownBadge/CountdownBadge.js, src/components/xl8/Xl8.js
fixes #826 - extra space in the translation results
simple fix to remove a space in the returned tag and value from the xl8 tag. Also removed unused className props from the badge.
=> rem erroneous space in translation return

src/App.js, src/components/kanban/Kanban.js, src/pages/poe/POE.js
-Moved title, filterform, main to poe page
-matched other page functions for the site
-changed how values passed to kanban element
-added default page to poe route
=> Refactoring POE page
