US-CBP/GTAS-UI

- src/App.js
- src/components/header/Header.js
- src/components/labelledInput/LabelledInput.js
- src/pages/admin/manageUsers/changePassword/ChangePassword.js
- src/pages/admin/manageUsers/changePassword/ChangePassword.scss
- src/services/serviceWrapper.js
- To test this PR locally, please pull the latest for the backend
> Change password

- src/pages/admin/manageUsers/ManageUsers.scss
- src/pages/admin/manageUsers/UserModal.js
minor edit user layout updates.
> fix #85 and update roles layout to 3 cols to save vertical space

- src/components/header/Header.js
> Header - mark the admin and tools menus when subitems are selected

- src/pages/paxDetail/notification/Notification.js
- src/pages/vetting/Vetting.js
- src/pages/vetting/review/Review.js
- src/services/serviceWrapper.js
> Fix duplicate api call

- src/pages/admin/noteTypeCats/NoteTypeModal.js
- src/pages/admin/watchlistCats/WatchlistModal.js
- src/utils/constants.js
Fix layout of WL Category and Note Type Categories modals. Using form cancel button now.
> replace Modal button with Form default cancel button

- src/App.js
- src/components/header/Header.js
- src/pages/admin/signUpRequests/SignUpRequests.js
- src/pages/login/Login.js
- src/pages/signUp/SignUp.js
- src/pages/signUp/SignUp.scss
- src/services/serviceWrapper.js
Please get the latest for the backend and update your db if you test this locally!
> User registration

- src/pages/admin/manageUsers/UserModal.js
- src/pages/admin/manageUsers/changePassword/ChangePassword.js
- src/pages/admin/noteTypeCats/NoteTypeModal.js
- src/pages/admin/settings/Settings.js
- src/pages/admin/watchlistCats/WatchlistModal.js
- src/pages/paxDetail/addToWatchList/AddToWatchlist.js
- src/pages/paxDetail/createManualHit/CreateManualHit.js
- src/pages/paxDetail/evenNotesModal/EventNotesModal.js
- src/pages/signUp/SignUp.js
- src/pages/tools/watchlist/WLModal.js
> update parents of Form component for new callback

- src/components/queryBuilder/QBUtils.js
- src/pages/tools/queryrules/Rules.js
Fix state loss when launching the QBModal from Rules page that was causing some occasional missing condition data in the QB component.
Cleaned up var names for clarity
Fixes #127
> fix state issues in Rules

- src/components/table/Table.css
- src/components/table/Table.js
- src/pages/admin/codeEditor/airport/Airports.js
- src/pages/admin/codeEditor/carrier/Carriers.js
- src/pages/admin/codeEditor/country/Countries.js
- src/pages/admin/manageUsers/ManageUsers.js
- src/pages/admin/manageUsers/changePassword/ChangePassword.scss
- src/pages/login/ForgotPassword.js
- src/pages/login/Login.scss
- src/pages/paxDetail/evenNotesModal/EventNotesModal.js
- src/pages/paxDetail/pnr/PNR.js
Resolves #56 ,  #144 ,  #139 , #145 
- Added column filter functionality on **Table** component
- Changed raw PNR title from **Segment Table** to  PNR's record locator number and version if available
- Ability to filter code editor's data
- Removed **DELETED** note type from note type options 
- Added cancel button to password reset page
- Disable Edit column from filtering and sorting data (`disableFilters, disableSortBy` should be set to true)
> Table filter

- src/pages/admin/settings/Settings.js
dropped the unused cols per Dave.
> remove unused cols for #181

- src/pages/paxDetail/addToWatchList/AddToWatchlist.js
- src/pages/paxDetail/changeHitStatus/ChangeHitStatus.js
- src/pages/paxDetail/createManualHit/CreateManualHit.js
minor fix to allow clickout closing of modals
> removed static background prop, fixes #186

- src/pages/paxDetail/createManualHit/CreateManualHit.js
locked the top two fields, minor gui cleanup.
> readonly ID fields, gave all field/label pairs the same layout

- src/components/countdownBadge/CountdownBadge.css
- src/components/countdownBadge/CountdownBadge.js
> fix sign placement, fix rounding error

- src/App.js
- src/pages/admin/Admin.css
- src/pages/admin/Admin.js
- src/pages/tools/Tools.css
- src/pages/tools/Tools.js
basic layout update for Tools and Admin landing page cards. Fixes #193
> restyle cards, center container

- src/components/main/Main.css
- src/components/main/Main.js
- src/pages/admin/fileDownload/FileDownload.js
- src/pages/admin/manageUsers/ManageUsers.js
- src/pages/admin/noteTypeCats/NoteTypeCats.js
- src/pages/admin/watchlistCats/WatchlistCats.js
- src/pages/paxDetail/PaxDetail.js
- src/pages/tools/queryrules/Queries.js
- src/pages/tools/queryrules/Rules.js
- src/pages/tools/watchlist/Watchlist.js
- src/pages/vetting/Vetting.js
minor layout fix. Use Main component with className "full" for full-width full-page grids.
Fixed layouts for all relevant pages under Admin and Tools, but there may be others.
> standardize grid page layouts in admin/tools

- src/App.js
- src/components/inputs/checkbox/Checkbox.js
- src/components/inputs/checkboxGroup/CheckboxGroup.js
- src/components/inputs/checkboxGroup/GroupCheckBox.js
- src/pages/admin/manageUsers/UserModal.js
- src/utils/constants.js
-adjusted checkboxes, made init function to enable default values
-changed user modal to allow for default values (disabling of checkboxes)
> Initial view flights role re-add.

- src/components/inputs/LabelledDateTimePickerStartEnd/LabelledDateTimePickerStartEnd.js
-We're replacing this soon I believe, but it didn't actually update the date-range, making testing impossible.
> Small fix to datetimepicker range used for Audit/Error log.

- src/pages/tools/queryrules/QRModal.js
- src/pages/tools/queryrules/Rules.js
fixes #231 added missing bag count element, sorted remaining alphabetically.
> fix missing baggage field, fixes #231

- src/components/raqb/RAQB.js
- src/utils/utils.js
translations in QB. Fixes #283
> translations in QB

- src/pages/paxDetail/PaxDetail.js
minor - changed the xid code for the page title. Fixes #290
> updated the translation code

- src/pages/tools/queryrules/QRModal.js
Removed the Travel Frequency field under Passengers in the QBRB
> remove traveler frequency field from pax

- src/i18n.js
config setting change. Converted hardcoded loadpath to use the env variable for the base url.
> Translation config - set loadpath to env var

- src/components/raqb/config.js
change == to "Equals", != to "Not Equals" in the rule builder
> change QBRB condition syntax

- src/components/table/Table.js
- src/pages/flightPax/FlightPax.js
- src/pages/flights/Flights.js
This is for #13 GTAS-UI as well as general flight-grid parity with hit display with the original UI.
There is a back-end pull request of the same branch name as well.
> Flight pax grid parity

- src/components/toast/Toast.js
- src/components/toast/Toast.scss
- src/pages/admin/manageUsers/ManageUsers.js
- src/pages/tools/queryrules/QRDetails.js
Added toast warning when query results exceed query return limit
-corrected to dev merge
> Query Over Limit Toast

- src/App.css
fix for #357, horizontal scrollbar too thick
> add height tag

- src/pages/vetting/review/Review.js
converted the review modal to the component, added with restrictions to it. Fixes #362
> fix the width on the last modal

- src/pages/paxDetail/notification/Notification.js
minor adjustment to the alignment of the notes input field on the notifications modal.
> fix note input style

- src/components/sidenavContainer/SidenavContainer.scss
minor - padding for sidenav got overwritten.
> fix missing css padding

- src/components/form/Form.js
- src/components/table/Table.js
- src/pages/admin/loaderStats/LoaderStats.js
- src/pages/admin/settings/Settings.js
- src/services/serviceWrapper.js
Fix Admin Settings error on submit
Fix Loader Stats refresh button not refreshing
fix duplicated xid tags in settings
added spinner to Form while fetches are pending
Added confirmation modal params for message and header
> fix forms errors, add spinners

- src/components/loading/Loading.css
- src/components/loading/Loading.js
- src/components/loading/Loading.scss
Dave's terrible spinner which now replaces my awesome one.
Set your network speed to slow 3g or fast 3g on a table page like vetting or flights to see it. Kept it wco blue, so no rainbow colors, but I'll take requests.
> Dave's terrible spinner

- src/App.css
- src/components/countdownBadge/CountdownBadge.js
- src/components/header/Header.scss
- src/components/navBar/NavBar.css
- src/components/title/Title.css
- src/pages/flightPax/FlightPax.js
- src/pages/flights/Flights.js
- src/pages/vetting/Vetting.js
add the direction icon to countdowntimer
> add countdowntimer direction icon

- src/components/segmentTable/SegmentTable.css
- src/components/segmentTable/SegmentTable.js
- src/pages/paxDetail/pnr/PNR.js
gives the cards more room on the PNR page. #414
> minor - make segment table narrower

- src/App.js
- src/pages/paxDetail/changeHitStatus/ChangeHitStatus.js
- src/pages/tools/Tools.js
- src/pages/vetting/Vetting.js
- src/pages/vetting/review/Review.js
- src/utils/constants.js
issue #391 , restrict access to Review modal on the PVL to admins and Hit Managers.
awaiting confirmation from Dave and Jon that we don't need Case Manager role access.
> restrict access to Review, replace case mgr access with hit mgr

- src/pages/paxDetail/createManualHit/CreateManualHit.js
> width on the modal

- src/pages/search/Search.js
gave the search page the same container and layout as the other grid based pages.
> update search layout to standard

- src/pages/admin/fileDownload/FileDownload.js
> fix date format, disable action col sort

- src/App.css
- src/pages/admin/Admin.css
- src/pages/tools/Tools.css
minor - reset the justification of the admin tiles so there's no big gaps between the rows. Moved duplicated css classes up to app.
> centralize css classes, update tile justification

- src/pages/admin/settings/Settings.js
- src/pages/admin/settings/settingModal.js
> read only view for settings, and added edit modal

- src/pages/admin/Admin.css
- src/pages/admin/signUpRequests/SignUpRequestModal.js
> display roles in 2 columns on signup approve modal

- src/pages/paxDetail/summary/Summary.js
> update event note card headers

- src/App.js
- src/pages/tools/queryrules/QRModal.js
- src/pages/vetting/Vetting.js
minor - fixes #459 and #460 and #461
> rename vetting hit types and admin file download

- src/components/raqb/utils.js
Fixes #455 , issue with the qbrb incorrectly converting "0" and "1" strings to boolean.
> fix string to bool conversion

- src/pages/flightPax/FlightPax.js
- src/utils/utils.js
fixes #482 . flightpax DOB col sorts by full date and filters by the displayed date format.
> fix sort and retail filtering by locale date format

- src/pages/paxDetail/summary/Summary.js
Historical hits card should display the correct data now!
> fixed historical hits bug

- src/pages/paxDetail/PaxDetail.js
Added spinner on the side nav to indicate a new data is loaded.
Is this sufficient for #470 ?
> Added spinner to pax details side nav

- src/pages/tools/queryrules/QRDetails.js
add missing flightnum, eta, etd cols to qr dev
renamed the hit columns to titlecased
added missing xl8 tags to the grid header
fixes #493
> add missing columns, add missing xl8 tags

- src/pages/paxDetail/notification/Notification.js
- src/services/serviceWrapper.js
> Multiple users notification

- src/components/filterForm2/FilterForm.js
- src/pages/admin/auditLog/AuditLog.js
- src/pages/admin/errorLog/ErrorLog.js
- src/pages/vetting/Vetting.js
> Reset dete time picker when clicking on reset

- src/pages/tools/queryrules/QRModal.js
- src/pages/tools/queryrules/QueryRules.css
fixes #500 
to test, go to Rules or Queries and click the **add new** button. to open the modal.
- Rules -- Without touching any of the inputs, click **Save** and verify the Title, Category, and Conditions (required fields) get highlighted in red.
- Queries -- Without touching any of the inputs, click **Save** and verify the Title and Conditions get highlighted red.
> fix QBRB title not validating input consistently

- src/components/cardWithTable/CardWithTable.js
- src/components/cardWithTable/CardWithTable.scss
- src/pages/paxDetail/summary/Summary.js
- Resolves #72 
- Partially resolves #484 (We are still disabling **Create Manual Hit** for passengers who have hits).
- I think we should close #484 and open another ticket for reviewing when we should enable Manual Hit creation.
> Fix/pax details/refresh hit summary

- src/pages/search/Search.js
> Fxed column filter by eta and etd

- src/App.js
- src/components/errorBoundary/ErrorBoundary.js
remove unused tags from root - temp fix. This will not affect a local build but should eliminate the whitespace caused by the wrapper tags at root when deployed.
> remove h1 tags from root

- src/pages/admin/manageUsers/UserModal.js
We need to change the seed data on the backend to include View flight role for `gtas` user.
> default View Flight Role for all users.

- src/pages/admin/signUpRequests/SignUpRequestModal.js
- src/pages/admin/signUpRequests/SignUpRequests.css
Fixes #564 
Corrected the modal layout. Did not replace it.
> fix existing modal

- src/pages/admin/signUpRequests/SignUpRequests.js
> add email field

- src/App.js
- src/components/header/Header.js
- src/pages/admin/Admin.js
hide kibana and neo4j tiles when the urls are not found
fixes #601
> fix blank admin pages

- src/pages/tools/queryrules/QRModal.js
- src/pages/tools/queryrules/QueryRules.css
> Updated date fields to use date picker

- src/App.js
- src/pages/login/ForgotUsername.js
- src/pages/login/Login.js
- src/services/serviceWrapper.js
- src/utils/constants.js
Test this PR agains `forgot-username` branch on the backend.
> Forgot username

- src/components/seatChart/searchSeat/SearchSeat.js
Followed your suggestion to avoid future code complication. 
And probably this will solve the bug related to search by middle name which I couldn't reproduce locally but exists on dev env.
> Fixed a potential problematic code structure

- src/pages/tools/watchlist/WLModal.js
fixes #635
corrected the dob date format on submit.
> reformatted the dob

- src/components/seatChart/SeatChart.js
- src/components/seatChart/searchSeat/SearchSeat.js
- src/components/seatChart/seatInfo/SeatInfo.js
This fixes #637 and the duplicate co-traveller bug
> Fixed middle name display issue

- src/components/filterForm2/FilterForm.css
- src/components/inputs/Inputs.scss
> fixed layout issue

- src/pages/tools/queryrules/QRModal.js
This is a companion PR to https://github.com/US-CBP/GTAS/pull/2013.
> Add UTC offset. This allows the backend to use DOB instead of AGE on queries

- src/pages/vetting/Vetting.js
fixes #668 
Remove the sort/filter functions from the Actions col on Vetting
> disable sort on vetting col

- src/components/loading/Loading.js
- src/components/loading/Loading.scss
- src/pages/vetting/Vetting.js
Fixes #666, the unholiest of all tickets - an ugly janky spinner.
Updated the css to make the loading spinner animation pretty, plus added back duration colors Dave asked for using 3 of our theme colors.
Please note that because of the way react updates the dom, there will sometimes still be some jitter as the page first loads. Each time the dom refreshes it triggers the animation to restart, so you may see it rapidly reset in the first second or so. After its done loading, however, the remainder of the animation should be smooth.
> fix spinner animation jank

- package-lock.json
- src/App.scss
- src/components/icons/InputValidationIcon.js
- src/components/inputs/text/Text.js
- src/components/labelledInput/LabelledInput.js
- src/components/overlay/Overlay.js
- src/components/overlay/Overlay.scss
- src/pages/admin/manageUsers/UserModal.js
- yarn.lock
This is to get inline form validation work on our apps.  For now, only password field on `**add user modal**` is being validated. If you like this approach, I can add validation to any of the inputs as long as we know what the constraints for that field are.
Please, test it locally and let me know if you have any suggestions.
> Inline input validation

- src/pages/vetting/Vetting.js
fixes #686 - Vetting biographic info sort bug
minor - updated the sort to use the last name column
> sort by last name

- src/pages/tools/watchlist/Watchlist.js
Resolves #711 (Actually it resolves the comment @sylbakar made on the ticket)
> Fixed dob filter

- src/components/header/Header.js
> Prevent page refreshing when pressing enter

- src/components/header/Header.js
- src/components/header/Header.scss
better align the brand logo, omnibox, and text vertically
fixes #745
> header vertical alignment

- src/pages/flights/Flights.js
> Reorder flight table column

- src/pages/flightPax/FlightPax.css
- src/pages/flightPax/FlightPax.js
fixes #757 - put the carrier name in the flightpax sidebar
> carrier name from lookup in flightpax sidebar

- src/App.scss
- src/components/countdownBadge/CountdownBadge.js
- src/components/flightBadge/FlightBadge.js
- src/pages/vetting/Vetting.js
- src/pages/vetting/biographicInfo/BiographicInfo.js
- src/pages/vetting/biographicInfo/BiographicInfo.scss
Fixes #790 - misc Table layout issues. See ticket for bug list
> Misc Table layout issues

- src/pages/vetting/Vetting.js
Fixes #793 Vetting timer sort not working
Timer sort was broken when the extra fields were removed. Updated it to calculate the countdown time with the existing fields.
> fix broken timer sort

- src/components/table/Table.js
- src/pages/admin/signUpRequests/SignUpRequests.js
- src/utils/constants.js
> hide action column when filter by approved/rejected status

- src/components/kanban/Kanban.css
- src/components/kanban/Kanban.js
-Made POE scroll horizontally
-increased vertical height of poe lanes
-moved element specific style to the governing css file.
resolves #828
> Poe horizontal scroll shift

- src/pages/admin/auditLog/AuditLog.js
- src/pages/admin/errorLog/ErrorLog.js
- src/pages/paxDetail/uploadAttachment/UploadAttachment.js
- src/utils/utils.js
-added new columns to upload attachment table
-added seconds to audit log timestamp
Has sister GTAS side PR that must be run.
fixes #703 #570
> Added new elements to attachment table, changed audit log timestamp

- src/App.scss
fixes #838 - forgot username error text incorrect
see backend PR [2065](https://github.com/US-CBP/GTAS/pull/2065)
- remove error text added during testing in a previous update (backend)
- fix text spillover edge case
> fix alert wrap and remove raw error text

- src/pages/poe/POE.js
Update POE to have a port picker.
> #854 - Add port to POE page
